version: '3.9'

services:
  web:
    build: ./Docker/web
    ports:
      - 80:5000
    volumes:
      - ./evobot:/usr/src/app
    command: python main.py

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: HardPassIsUgly
    volumes:
      - ./data/mongo:/data/db
