version: '3.9'

services:
  web:
    build: ./Docker/web
    ports:
      - "80:5000"
    volumes:
      - ./:/usr/src/app
    command: python main.py

  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
